language: ruby

before_install:
  - npm install

rvm:
  - 2.0.0
  - 2.1.7
  - 2.2.8
  - 2.3.5
  - 2.4.2

sudo: false
cache: bundler

script:
 - bundle exec rake test
 - script/test

gemfile:
  - Gemfile.rails32
  - Gemfile.rails40
  - Gemfile.rails41
  - Gemfile.rails42
  - Gemfile.rails50

matrix:
  exclude:
    - gemfile: Gemfile.rails50
      rvm: 2.0.0
    - gemfile: Gemfile.rails50
      rvm: 2.1.7
    - gemfile: Gemfile.rails40
      rvm: 2.4.2
    - gemfile: Gemfile.rails41
      rvm: 2.4.2
